# **PART 1: Làm quen với PyTorch**

## **Task 1.1: Tạo Tensor**

In [15]:
import torch
import numpy as np

# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")

# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.3941, 0.2430],
        [0.6930, 0.3968]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


## **Task 1.2: Các phép toán trên Tensor**

In [16]:
print("x_data + x_data =\n", x_data + x_data, "\n")
print("x_data * 5 =\n", x_data * 5, "\n")
print("x_data @ x_data.T =\n", x_data @ x_data.T)


x_data + x_data =
 tensor([[2, 4],
        [6, 8]]) 

x_data * 5 =
 tensor([[ 5, 10],
        [15, 20]]) 

x_data @ x_data.T =
 tensor([[ 5, 11],
        [11, 25]])


## **Task 1.3: Indexing & Slicing**

In [17]:
print("Hàng đầu tiên:", x_data[0])
print("Cột thứ hai:", x_data[:, 1])
print("Phần tử (hàng 2, cột 2):", x_data[1, 1])

Hàng đầu tiên: tensor([1, 2])
Cột thứ hai: tensor([2, 4])
Phần tử (hàng 2, cột 2): tensor(4)


## **Task 1.4: Thay đổi hình dạng Tensor**

In [18]:
x = torch.rand(4, 4)
print("Tensor ban đầu:\n", x)

reshaped = x.view(16, 1)
print("\nTensor reshape về (16,1):\n", reshaped)

Tensor ban đầu:
 tensor([[0.4705, 0.2475, 0.6855, 0.6793],
        [0.2056, 0.2558, 0.2301, 0.5821],
        [0.5161, 0.3319, 0.2214, 0.9807],
        [0.8946, 0.6802, 0.8941, 0.8551]])

Tensor reshape về (16,1):
 tensor([[0.4705],
        [0.2475],
        [0.6855],
        [0.6793],
        [0.2056],
        [0.2558],
        [0.2301],
        [0.5821],
        [0.5161],
        [0.3319],
        [0.2214],
        [0.9807],
        [0.8946],
        [0.6802],
        [0.8941],
        [0.8551]])


# **Phần 2: Tự động tính Đạo hàm với autograd**

## **Task 2.1: Thực hành với autograd**

In [26]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")
 
# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")
 
# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")
 
# Thực hiện thêm các phép toán
z = y * y * 3
 
# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))
# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x00000189312EEEC0>
Đạo hàm của z theo x: tensor([18.])


Nếu gọi z.backward() lần nữa mà không đặt retain_graph=True => PyTorch sẽ báo lỗi:

RuntimeError: Trying to backward through the graph a second time...

Vì backward() mặc định giải phóng computational graph sau khi tính xong gradient.

# **PHẦN 3 - Xây dựng Mô hình đầu tiên với torch.nn**

## **Task 3.1: Lớp nn.Linear**

In [28]:
import torch.nn as nn

# Lớp Linear 5 => 2
linear_layer = nn.Linear(in_features=5, out_features=2)

# Input mẫu
input_tensor = torch.randn(3, 5)

# Truyền qua layer
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n{output}")


Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
tensor([[ 0.6914, -0.7003],
        [ 0.4259,  0.1257],
        [ 0.0410,  0.9257]], grad_fn=<AddmmBackward0>)


## **Task 3.2: Lớp nn.Embedding**

In [32]:
# Lớp nn.Embedding là một bảng tra cứu, dùng để ánh xạ các chỉ số của từ thành cácvector embedding.
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)
# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")


Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[-0.9508,  0.2817,  0.2133],
        [-2.4920,  0.4394, -0.2839],
        [-1.0632,  0.1701,  0.0445],
        [ 0.4540, -0.5628, -1.4228]], grad_fn=<EmbeddingBackward0>)


## ** Task 3.3: Kết hợp thành một nn.Module**

In [34]:
class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        embeds = self.embedding(indices)
        hidden = self.activation(self.linear(embeds))
        output = self.output_layer(hidden)
        return output

# Khởi tạo mô hình
model = MyFirstModel(
    vocab_size=100, 
    embedding_dim=16, 
    hidden_dim=8, 
    output_dim=2
)

# Input mẫu
input_data = torch.LongTensor([[1, 2, 5, 9]])

output_data = model(input_data)

print(f"Model output shape: {output_data.shape}")
print("Output dữ liệu:\n", output_data)


Model output shape: torch.Size([1, 4, 2])
Output dữ liệu:
 tensor([[[-0.0942, -0.0116],
         [-0.4026, -0.0383],
         [ 0.2365,  0.5539],
         [-0.5186, -0.1703]]], grad_fn=<ViewBackward0>)
